module Boxboxbox
end

class Boxboxbox::BinaryImage
  attr_reader name: String
  attr_reader binary: String

  def initialize: (name: String, binary: String) -> untyped
end

class Boxboxbox::Point
  attr_reader x: Float
  attr_reader y: Float

  def initialize: (x: Float x, y: Float y) -> untyped
end

class Boxboxbox::Box
  attr_reader image_name: String
  attr_reader top_left: Point
  attr_reader bottom_right: Point

  def initialize: (image_name: String, top_left: Point, bottom_right: Point) -> untyped
end

class Boxboxbox::Unzipper
  @target_extensions: ::Array[String]
  @target_extensions_regexp: Regexp
  @ignore_regexp: Regexp

  def initialize: (target_extensions: ::Array[String], ?ignore_regexp: Regexp) -> untyped
  def target_extensions_regexp: -> Regexp
  def unzip: (zip_path: Pathname) -> _Each[Boxboxbox::BinaryImage, nil]
end

interface _BoxLocalizer
  def localize: (images: ::Array[Boxboxbox::BinaryImage]) -> ::Array[Boxboxbox::Box]
end

Boxboxbox::Unzipper::TARGET_EXTENSION_REGEX: Regexp
Boxboxbox::Unzipper::MACOS_METADATA_PATTERNS: Regexp

class Boxboxbox::BoxLocalizer::GoogleVisionApiOnline
  @access_token: String
  @max_results: Integer
  @min_percentage: Float
  @max_retry: Integer
  @logger: Logger

  def initialize: (access_token: String, max_results: Integer, min_percentage: Float, max_retry: Integer, ?logger: Logger) -> untyped

  def localize: (images: ::Array[Boxboxbox::BinaryImage]) -> ::Array[Boxboxbox::Box]

  def exec_request: (images: ::Array[Boxboxbox::BinaryImage]) -> { success_boxes: ::Array[Boxboxbox::Box], failed_images: ::Array[Boxboxbox::BinaryImage] }

  def vertices2box: (image_name: String, vertices: ::Array[{x: Float, y: Float}]) -> Boxboxbox::Box

  def response2person_vertices: (response_body: String) -> ::Array[::Array[{x: Float, y: Float}]]

  def generate_request: (image_content: String) -> Typhoeus::Request
end

class Boxboxbox::BoxPresenter::Csv
  def present: (boxes: ::Array[::Boxboxbox::Box]) -> String
end

Boxboxbox::BoxLocalizer::GoogleVisionApiOnline::URL: ::String

Boxboxbox::BoxLocalizer::GoogleVisionApiOnline::PERSON_LABEL: ::String
